### ISSUE TITLE
Add events to buttons for tracking engagement

### ISSUE THREAD

**Issue by signechambers1** [chanzuckerberg/single-cell-data-portal#1882]
Add events to the Organism filter, Add Tissue and Add genes buttons to track engagement.

⚠️⚠️⚠️WARNING⚠️⚠️⚠️
1. Before deploying to prod, make sure to update https://plausible.io/cellxgene.cziscience.com to add events under `Goals`

- [ ] WMG_SELECT_GENE
- [ ] WMG_SELECT_ORGANISM
- [ ] WMG_SELECT_TISSUE
- [ ] WMG_CLICK_NAV (missing top level nav button now)
- [ ] WMG_HEATMAP_LOADED

**Comment by tihuan** [comment]
PR: https://github.com/chanzuckerberg/single-cell-data-portal/pull/2282
