### ISSUE TITLE
Docs Epic

### ISSUE THREAD

**Issue by seve** [chanzuckerberg/single-cell-data-portal#2587]
- [x] #2585 
- [x]  Clean up `.mdx` files to match standards and render properly
   - [x] File names
   - [x]  Images
   - [x]  Tables
- [x] #2618 
- [x] #2584 
- [x] #2619
- [x] Allow for expanding and collapsing of directories in the sidebar
- [ ] Edit the navigation sidebar to allow for hiding when viewport shrinks
- [ ] #2586  (P1)
- [ ] #2601
