### ISSUE TITLE
Productionize Cell Census builder

### ISSUE THREAD

**Issue by metakuni** [chanzuckerberg/single-cell-data-portal#3636]
- [ ] Productionize the [Cell Census Builder MVP](https://github.com/chanzuckerberg/soma-scratch/blob/main/experiments/make_cell_census/REAMDE.md) developed in 2022Q4 and deploy it to production
- [ ] Implement automated compatibility and data availability tests for the Cell Census:
  - [ ] Cell Census v1 access via SOMA API
  - [ ] Cell Census v1 access via Cell Census API
  - [ ] Cell Census v1 access via Gene Expression
- [ ] Prepare analytics infrastructure to monitor Cell Census usage (downloads only)
- [ ] Generate and publish the Cell Census v1 to `s3://cellxgene-data-public`

**Comment by metakuni** [comment]
Closing this epic since the decision was to pivot and have Emanuele and Trent contribute directly to Cell Census.
