### ISSUE TITLE
Deploy redesigned Portal

### ISSUE THREAD

**Issue by metakuni** [chanzuckerberg/single-cell-data-portal#3665]
Scope:
- [x] Verify that [curation API notebooks](https://github.com/chanzuckerberg/single-cell-curation/tree/main/notebooks/curation_api) still work
- [x] Final QA, including PM sign off
- [x] Migrate all data
- [x] Deploy the redesigned Portal to production

Note: This is a continuation of #3433 but represented here as a separate epic for visibility on the [Q1 roadmap](https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/roadmap)
