### ISSUE TITLE
Gene Expression Compare Functionality

### ISSUE THREAD

**Issue by signechambers1** [chanzuckerberg/single-cell-data-portal#3725]
**Goal**
Allow users to compare gene expression within a cell type across supported metadata fields (Disease, Self-Reported Ethnicity, Sex).

**Why are we building this?**
Users want to be able to see how expression compares across datasets or categorical variables like sex, etc to see how consistent the expression patterns are and identify differences across categories. This is one of our top requested feature for Gene Expression (4 survey responses and came up multiple times in the initial user research). While users can use filters and compare two different windows, this is a clunky experience. We'd like to seamlessly allow users to compare gene expression within a cell type across supported metadata fields (Disease, Self-Reported Ethnicity, Sex). 

**Product requirements**
- [x] #4112
    - [ ] Users can clear the Selected Dimension
    - [ ] The Selected Dimension will reflect any applied filters
    - [ ] Users can only select one Selected Dimension at a time (in a future improvement we may want to allow for multiple)
    - [ ] Analytics should track the usage of this functionality, and what dimensions users are selecting. We expect ~20% of weekly engaged visitors to use this feature, similar to download functionality.

- [x] #4113
    - [ ]  Tool tip includes the Selected Dimension
    - [ ] Once selected, users can view gene expression and percent of cells expressed for the cell types within in the tissues selected

- [x] #4115

- [x] #4116
    - [ ] Marker genes will not be available for cell types with a selected dimension (we will likely want to enable this in the future)
    - [ ] Rows where cell type + dimension is not measured will be omitted (ie if we have no disease data for naive b cells and the user selects dimension = Disease, only the line Healthy will be displayed)

- [x] #4117
    - [ ] The Selected Dimension will work with existing functionality (sort cell types, sort genes, color scale, download)
    - [ ] The updated dot plot with Selected Dimension will load interactively, or show a loading indicator. Eng, prod and design will iterate on this requirement if data takes more than a few seconds to load.
    - [ ] When a user shares a URL for a dot plot, compare functionality should be incorporated so a shared URL will reflect the selected dimension. 

**Testing Plan** 
Product tests listed [here.](https://docs.google.com/spreadsheets/d/14s4VoZA4LmDf5xybupCp-R7erqkIAQHG2E8kTw_jj1Q/edit#gid=0)

No additional SME validation is required as the underlying data has already been validated.

[**Figma**](https://www.figma.com/file/blyEMZDsi7EMopyyIX4XAg/Q1-2023-Gene-Expression-Improvements?node-id=1%3A182751&t=HyhVi2K7HrQEOKpd-0)

**Comment by ashin-czi** [comment]
Organized the different tasks into sub categories, but items can be moved around if deemed fit somewhere else

**Comment by signechambers1** [comment]
In discussion today with @ashin-czi and @hthomas-czi we will not implement the Dataset Option for Compare. Instead, we will prioritize adding a publication filter and adding publication as an option for Compare at that point.

**Comment by signechambers1** [comment]
Also in the UI we will call this feature Group by. @karenliang0 to update designs
