### ISSUE TITLE
Upgrade to Python 3.10

### ISSUE THREAD

**Issue by atolopko-czi** [chanzuckerberg/single-cell-data-portal#4131]
## Motivation

Language features availability, performance, security

## Definition of Done

Data Portal runs w/o issue on 3.10, including BE and pipelines

## Tasks

- [ ] Docker containers updated
- [ ] Linters updated (to check against 3.10 compliance)
- [ ] Documentation updated
- [ ] Full system testing performed on rdev

**Comment by metakuni** [comment]
Created a companion issue to upgrade Explorer:
* https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/gh/chanzuckerberg/single-cell-explorer/564

**Comment by metakuni** [comment]
@dsadgat , I added the `gene expression` label since this impacts GE, unless it's decoupled from Portal before this Python upgrade is done.

**Comment by ebezzi** [comment]
The data portal backend is already using Python 3.10 and does not need an upgrade. The pipeline is using 3.8 but to upgrade it painlessly, we'd need to change the base Docker image to Ubuntu 22 (currently, we're using Seurat's base image which is based on Ubuntu 20). This might not be worth it especially with Seurat 5 now being in beta.

`Dockerfile.data_cube_creation` is based on a python 3.9 image - is this what we want to upgrade?

**Comment by atolopko-czi** [comment]
Sound good if data_cube_creation is all we need to (and can reasonably) upgrade.
