### ISSUE TITLE
Fix TestAPI functional test failures

### ISSUE THREAD

**Issue by atolopko-czi** [chanzuckerberg/single-cell-data-portal#4313]
## Motivation

Deployment process is taking too long due to flakey functional test failures

## Definition of Done

The functional test failures, listed below, run reliably.

## Tasks

- [ ] `ERROR: test_collection_flow (tests.functional.backend.corpora.test_api.TestApi) [Test make collection public]`
```
  File "/single-cell-data-portal/tests/functional/backend/corpora/test_api.py", line 105, in test_collection_flow
    res.raise_for_status()
  File "/usr/lib/python3/dist-packages/requests/models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 504 Server Error: Gateway Time-out for url: https://api.cellxgene.dev.single-cell.czi.technology/dp/v1/collections/6b026c41-5fd1-454b-93db-3fd113a7159f/publish
```
- [ ] `ERROR: test_collection_flow (tests.functional.backend.corpora.test_api.TestApi) [Test everyone can retrieve a public collection]`
```
  File "/single-cell-data-portal/tests/functional/backend/corpora/test_api.py", line 128, in test_collection_flow
    self.assertIn(canonical_collection_id, collection_ids)
UnboundLocalError: local variable 'canonical_collection_id' referenced before assignment
```
- [ ] `ERROR: test_collection_flow (tests.functional.backend.corpora.test_api.TestApi) [Test a public collection can be tombstoned]`
```
  File "/single-cell-data-portal/tests/functional/backend/corpora/test_api.py", line 131, in test_collection_flow
    res = self.session.delete(f"{self.api}/dp/v1/collections/{canonical_collection_id}", headers=headers)
UnboundLocalError: local variable 'canonical_collection_id' referenced before assignment
```

**Comment by atolopko-czi** [comment]
All of the test failures have the same root cause, the timeout of the `https://api.cellxgene.dev.single-cell.czi.technology/dp/v1/collections/<ID>/publish` call.

**Comment by atolopko-czi** [comment]
This is a dup of https://github.com/chanzuckerberg/single-cell-data-portal/issues/4219, but keeping this as a separate issue for what may be only a temporary fix to get tests healthy again.

**Comment by atolopko-czi** [comment]
Func tests appear to be sending repeated cloudfront invalidation requests: [logs](https://us-west-2.console.aws.amazon.com/cloudwatch/home?region=us-west-2#logsV2:log-groups/log-group/$252Fdp$252Fdev$252Fdevstack$252Fbackend/log-events/fargate$252Fweb$252Fe4d55d04d5ef408689c5c6927bda63e8$3Fstart$3D1678213985299$26refEventId$3D37425422476993690543132431633851021345337034079700123648$26filterPattern$3D$2522Requesting+invalidation$2522). However, they are spaced minutes apart, so volume of invalidations is probably not a root cause.

**Comment by atolopko-czi** [comment]
Re-ran func tests 3 times **successfully** on dev/main branch GHA and once on staging branch GHA, after increasing the response timeout to 60 secs. Applying to prod now as well.  Although these tests are not run on prod, it's best to have consistent CloudFront settings across the deployment environments.
