### ISSUE TITLE
Update RDS to the latest version

### ISSUE THREAD

**Issue by atolopko-czi** [chanzuckerberg/single-cell-data-portal#4476]
## Motivation

All the reasons to keep infra up-to-date: security, bug fixes, performance, etc. And Central Infra has explicitly requested we upgrade now.

## Definition of Done

- RDS version is at latest supported version for Single-Cell RDS clusters
- Terraform is updated and future runs will not attempt to back-rev.

## Tasks

For each env:
- [x] Using the AWS Console, create a snapshot before the update, just in case something goes wrong.
- [x] Update the Engine Version using the AWS Console, and not Terraform, since the Terraform Module sometimes allows backward selection which will throw an error. Choose the latest version available, unless there is an absolute need for a lower version (this will keep your team out of harms way for longer when AWS deprecates engine versions)
- [x] Update Terraform code to bring it up to date with the actual version (see [past example](https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/gh/chanzuckerberg/single-cell-infra/730))
- [x] Revise [on-call docs](https://docs.google.com/document/d/1n5cngEIz-Lqk9737zz3makXGTMrEKT5kN4lsofXPRso/edit#heading=h.x8ouhpf1ve7v) with any updated RDS upgrade instructions and include links to relevant articles that may be helpful for future upgrades
- [x] Notify central infra when all RDS instances have been upgraded

## Original Request from Central Infra

<img width="1071" alt="image" src="https://user-images.githubusercontent.com/29237884/229630266-1a2cff43-8767-4480-9123-5cf51ea8cde1.png">

**Comment by danieljhegeman** [comment]
[dev snapshot created](https://us-west-2.console.aws.amazon.com/rds/home?region=us-west-2#db-snapshot:engine=aurora-postgresql;id=rds-version-upgrade-backup)

**Comment by danieljhegeman** [comment]
[We are currently on 10.21](https://us-west-2.console.aws.amazon.com/rds/home?region=us-west-2#database:id=corpora-dev-corpora-api;is-cluster=true;tab=configuration:~:text=Engine%20version,10.21) using a [db.r4.large](https://us-west-2.console.aws.amazon.com/rds/home?region=us-west-2#database:id=corpora-dev-corpora-api;is-cluster=true;tab=configuration:~:text=us%2Dwest%2D2b-,db.r4.large,-Available) instance

[Amazon docs for engine upgrades for our instance type specify Lower than PostgresSQL 13](https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/Concepts.DBInstanceClass.html#Concepts.DBInstanceClass.Support:~:text=db.r4.large,than%20PostgreSQL%2013)

**Comment by danieljhegeman** [comment]
@atolopko-czi any indication from Central about whether we need to upgrade to 14? I think we will be required to change our instance type in order to do so.

**Comment by danieljhegeman** [comment]
It seems like db.r5.large is a superior instance type over our current db.r4.large, with essentially the same specs coming at a fractionally-cheaper price, and allowing for Postgres 14

**Comment by danieljhegeman** [comment]
Dev upgrade to 12.11 seems to have proceeded without any disturbances. Portal site loads fine after hard reload, collections load, etc.

**Comment by atolopko-czi** [comment]
v14 & r5.large sound good! ty.

**Comment by danieljhegeman** [comment]
All envs now running 12.11

**Comment by danieljhegeman** [comment]
On-call documentation updated with relevant AWS docs.
