### ISSUE TITLE
Improve WMG backend and pipeline tests

### ISSUE THREAD

**Issue by atarashansky** [chanzuckerberg/single-cell-data-portal#4516]
## Disclaimer
Initial estimates are added to the attached issues. These can be modified at will by the assigned engineer.

## Motivation
Tests are vital to achieve a reduction in the frequency of bugs and outages. They are especially important for our complex WMG processing pipeline as bugs here can be (a) more common (b) may prevent the pipeline from running and (c) corrupt the data that is being presented to the user. However, we currently have very low unit test coverage of the WMG processing pipeline. This has resulted in a number of pipeline bugs that required hotfixes and regeneration of the data snapshot. 

More generally, we have the following deficiencies in WMG tests:
- As mentioned, we have low unit test coverage of the WMG processing pipeline, primarily summary cubes and related data artifacts generation. 
- Certain outputs of the WMG processing pipeline are not validation tested, particularly the precomputed marker genes.
- We are missing some backend unit tests and functional tests.
- Some of our unit and processing tests are dependent on a static test fixture (particularly the marker gene tests). This is unwieldy as changes to this fixture require updating the hardcoded numbers in a few tests. 

More information here: [Assessment of WMG tests and plan for improvement](https://docs.google.com/document/d/1BYtJ736AJ8lvEP_cVNVAkmgchoD9xcYzuZXV404e7l8/edit#)

## Definition of Done

At minimum, this epic will be considered done when all tasks pertaining to adding new tests are completed. The tasks related to improving existing tests are also important but of lower priority.

## Tasks

- [ ] Scope out the snapshot creation functions that must be unit tested and design the testing infrastructure and required fixtures
  - [ ] Implement WMG snapshot creation unit tests
  - [ ] Implement the high-level snapshot creation unit test in TestCorpusLoad
- [ ] Add functional tests for the /filters and /markers endpoints
- [ ] Add unit tests for the function used to check if two cell types are in the same lineage of the cell ontology (are_cell_types_colinear)
- [ ] Add validation of precomputed marker genes to the pipeline validation tests
- [ ] Add unit tests for the function used to create high level tissues in the processing pipeline
- [ ] Design the mock test fixtures necessary to test marker gene calculation
  - [ ] Update marker gene calculation unit tests to use the mock test fixtures
  - [ ] Update the marker gene cube creation unit test to use the mock test fixtures
- [ ] Remove dependence on the realistic test fixture in query and API unit tests
- [ ] Update the names of secondary filter API unit tests to reflect the new “filters” endpoint 
- [ ] Update constants in the pipeline validation tests
