### ISSUE TITLE
Compare cell types across publications and filter by publication

### ISSUE THREAD

**Issue by signechambers1** [chanzuckerberg/single-cell-data-portal#4730]
**What is the problem?**
Our users would like to be able to compare cell types across publications in order to see where expression patterns are consistent and where they diverge. Understanding these patterns will help users to interpret results, filter by publications to narrow results if they want to, and download collections or datasets they are interested in.

This is a top feature request from our users, see user feedback [here](https://airtable.com/app8fNSQ8ieIiHLOv/tblqoYEr9Ee7rYrut/viwFPtZPfH7r2hIzk/rec5NZa4Orn1eKbay?blocks=hide).

**How does this align to single cell strategy?**
This functionality furthers researchers ability to identify patterns of expression across cell types, which is core to CELLxGENE Discover’s main goal.

**[Figma Prototype](https://www.figma.com/proto/nUbwlxcSPAGoRGWyYaIkyv/Q2-2023-Gene-Expression-Improvements?page-id=226%3A52176&node-id=226-58146&viewport=601%2C309%2C0.21&scaling=scale-down&starting-point-node-id=226%3A58146&show-proto-sidebar=1)**
**[Figma Designs](https://www.figma.com/file/nUbwlxcSPAGoRGWyYaIkyv/Q2-2023-Gene-Expression-Improvements?type=design&node-id=226-52176&t=jEufF2mpVSuHem46-0)**

**Definition of a publication**
* Each collection is associated with a publication (they have a 1:1 relationship)
* Publications are formatted as: First author last name. (year) Journal
* Example: Carr et al. (2023) Nature
* For collections without a publication DOI, we will use the last name of the collection contact, and no publilcation. Example: Carr et al. (2023) No publication

**User stories**
1. Users can filter by publication
- [x] User can multiselect from a publication filter and results shown in the dot plot will filter to the selected publications
- [x] User can clear publication selections
- [x] Filter works consistently with other filters in the left side bar
- [x] Analytics work: New event tracking the filter usage & values, update share & download to save state of filter (WMG_download_complete, WMG_share_clicked, WMG_share_loaded)

2. User can Group By a publication
- [x] User can select Publication as an option in the Group By option and dot plot will update showing rows for each publication for each cell type that is visible
- [x] Loading indicator is present if loading time is >1 sec
Iteration likely needed:
- [ ] _Iterate with product and design on performance and speed options_
- [ ] _Open question: Iterate with product and design to resolve UX complications where there are many publications per cell type_
- [ ] Analytics work: Update group by analytics event

**Definition of Success**
- ~40% of users use filters, need to talk to Amanda about expectations. My guess is this would replace some of the people using the dataset filter.
- I expect ~10% of engaged users to use Group By publication functionality (~20% of engaged users are using Group By functionality, expect this to increase slightly)

cc @signechambers1 for product, @karenliang0 for design, @ainfeld for analytics
