### ISSUE TITLE
Create an 'untombstone' utility

### ISSUE THREAD

**Issue by metakuni** [chanzuckerberg/single-cell-data-portal#4828]
## Motivation
Mistakes happen. If a collection is accidentally deleted, it should be easy for _any_ on-call engineer to be able to resurrect it. 

Thanks to the magic of immutable data, this is all we have to do: ([from @ebezzi in Slack](https://czi-sci.slack.com/archives/C024HCSH9PT/p1683758051542559?thread_ts=1683757407.222789&cid=C024HCSH9PT))
```
update persistence_schema."Collection" set tombstone=false where id='<collection ID>';
```

See also @Bento007's comment below re: recovery of S3 assets.

For quicker recovery after accidental deletions, it would be handy to have a script that can resurrect deleted data.

## Definition of Done
- [ ] Implement a script to make it easier for an on-call engineer to undo a deletion
- [ ] Add tests for the above
- [ ] Add instructions for use in [on-call docs](https://docs.google.com/document/d/1n5cngEIz-Lqk9737zz3makXGTMrEKT5kN4lsofXPRso/edit#heading=h.88nz21uu8s19)

## Tasks

Detail the specific tasks that can be used to accomplish the desired changes.
If detailed steps cannot be provided at this time, please file a [Tech Proposal](https://docs.google.com/document/d/1o2vuvl-kXwRJN1nBoPzJS_MAQgDGYnjmPZWa4qRDi-I/edit#heading=h.7dvzhm7gqc3v) instead.

- [ ]
- [ ]

**Comment by danieljhegeman** [comment]
It is not sufficient to simply make the necessary updates in the entity rows in postgres because the tombstoning process also removes the asset files from the public-access bucket `dataset-assets-public-<env>`; files will need to be restored to that bucket, by the correct naming convention, from the private assets bucket `corpora-data-<env>`.

For a given Dataset Version `abc.h5ad` that lives at `corpora-data-prod/abc/local.h5ad` in the private bucket, this will need to be copied to `dataset-assets-public-prod/abc.h5ad` because that file will have been deleted during the tombstoning action.

**Comment by Bento007** [comment]
Here is a script to restore a delete file from a versioned bucket:
```python
import boto3

s3 = boto3.client("s3")
dataset_ids = []  # TODO add datasets that need to be restored here

for dataset_id in dataset_ids:

    response = s3.list_object_versions(
        Bucket="dataset-assets-public-prod",
        Prefix=dataset_id)
    delete_markers = [i for i in response["DeleteMarkers"] if i["IsLatest"] == True]
    for marker in delete_markers:
        print("restoring", marker["Key"])
        response = s3.delete_object(
            Bucket="dataset-assets-public-prod",
            Key=marker["Key"],
            VersionId=marker["VersionId"])
        response.pop("ResponseMetadata")
        print(response)

```

**Comment by danieljhegeman** [comment]
Code-complete and adhoc tested, just need to add a unit test.

**Comment by danieljhegeman** [comment]
Confirmed working in dev
