### ISSUE TITLE
CellGuide - UI/UX Improvements

### ISSUE THREAD

**Issue by niknak33** [chanzuckerberg/single-cell-data-portal#5369]
Based on early feedback from CellGuide users and the internal program team, we want to make the changes/improvements to the CellGuide feature listed below. A lot of the feedback from users (internal/external), mentioned it was confusing/not easy to navigate and these issues are covered below.

- [x] [#5405](https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/gh/chanzuckerberg/single-cell-data-portal/5405) - Data Table "overflow" Tags
  - Both the Tissue and Disease columns should use the overflow Tag if there are three or more values
  - "Normal" value for Disease should be excluded from the overflow Tag and appear above it instead
- [x] [#5406](https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/gh/chanzuckerberg/single-cell-data-portal/5406) - Move HuBMAP and CZI labels from Marker Gene Tabs to Table footer inline with Pagination
- [x] [#5407](https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/gh/chanzuckerberg/single-cell-data-portal/5407) - Replace "Source: ChatGPT" Link with "Help" icon.
- [x] [#5408](https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/gh/chanzuckerberg/single-cell-data-portal/5408) - Replace scroll view with Pagination for Data section (same as Marker Genes)
- [ ] [#5409](https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/gh/chanzuckerberg/single-cell-data-portal/5409) - Ontology Tree
  - The size of the Cell Type node should correspond to the cell count for that Cell Type. Start with the formula we use to calculate the size of the dot plot in Gene Expression, but we may need to do a normalization of some sort
  - Update legend to match Figma
    - Add "Current" cell type
    - Add Cell Count
  - Change active edge color to `gray400`
  - Change inactive edge color to `gray300` (same color as inactive node)
  - Remove bold and italic styles from cell type labels
- [x] [#5410](https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/gh/chanzuckerberg/single-cell-data-portal/5410) - Minor UI fixes
  - Update TypographyStyles in [SDS theme file](https://github.com/chanzuckerberg/single-cell-data-portal/blob/main/frontend/src/common/theme.ts) according to [Figma](https://www.figma.com/file/JsWBZz7BuKhNcFqzYNJZLO/Single-Cell-Design-System?type=design&node-id=4757%3A40539&mode=dev)
  - Remove the divider under the Data section header
  - Update section header style to `fontHeaderL[600]`
  - Increase the padding between sections from `48px` to `80px`
  - Increase padding between search bar and In-Page Navigation from `20px` to `64px`
  - Change "Source Data" to "Data" on In-Page Navigation
- [x] [#5411](https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/gh/chanzuckerberg/single-cell-data-portal/5411) - Footer at the bottom of the Cell Type page

**UX Design**
[Figma – Overview](https://www.figma.com/file/ArNTXphy0CNBZLwb6O4YEW/CellGuide?type=design&node-id=1742%3A101334&mode=design&t=wtYAepVpUWpHXMR4-1)

Note: Engineers to add substories to this epic.

**Comment by atarashansky** [comment]
Do we pin "Normal" disease label to the top in the event that there is no tag?

**Comment by atarashansky** [comment]
<img width="893" alt="image" src="https://github.com/chanzuckerberg/single-cell-data-portal/assets/16548075/e7279e3b-0ff5-4d75-9266-e6856ce41310">
The references/citations should overflow I think?
