### ISSUE TITLE
Update Data Portal e2e tests config to work with rdev

### ISSUE THREAD

**Issue by tihuan** [chanzuckerberg/single-cell-data-portal#5454]
This work is about taking a working RDev E2E test script that can be run locally and making it run in GHA.

## DoD
E2E tests will run against rdev in PRs and on demand locally

## Tasks
- [ ] Update WMG conditional runs to allow rdev BE endpoint
- [ ] Accept rdev link through env var or something - `RDEV_LINK`
- [ ] Fix anything else that comes up
- [ ] Use dev Auth0 test account
- [ ] Make sure Playwright can get through Auth0 gate for rdev site
- [ ] Figure out if an rdev will be up in each PR, and how to only start e2e tests when the rdev is ready
- [ ] Make sure rdev has seeded published collections like dev/staging for logged in tests - use `python3 -m scripts.smoke_tests.setup` https://github.com/chanzuckerberg/single-cell-data-portal/blob/c3da69bf087d6ee00f7c7dc446155d0a82bd51e3/.github/workflows/deploy-happy-stack.yml#L136
- [ ] Run logged in tests in rdev

**Comment by atolopko-czi** [comment]
Many of the considerations (tasks) in this issue's description are covered by other issues.  The work to ensure that Portal E2E tests work in rdev is otherwise covered by https://github.com/chanzuckerberg/single-cell-data-portal/issues/5604, so closing this as a dup.
