### ISSUE TITLE
Front-end changes for DE v1

### ISSUE THREAD

**Issue by niknak33** [chanzuckerberg/single-cell-data-portal#6921]
UI changes required for the current prototype developed by Alec, this will allow us to test externally and internally (Higher Priority).

**Higher Priority**
- [x] Add Method dropdown
- [x] Add method information (need to nudge Sidney about this)
- [x] Dropdowns are not cross-filtering within the Cell Group which results in selections being cleared unknowingly (ex: select adipose, adrenal, and blood within tissues, and then select ‘abnormal cell’. This clears all tissues other than blood) 
- [x] Add ‘Open in Gene Expression’ link
  - (alec) Needs more design cycles
- [x] Add # of cells selected for each cell group
  - [x] Add loading spinner to left of # of cells when filters endpoint is loading
- [x] Remove inverse selection button (verify this decision with Alec)
- [x] Dropdown boxes should not expand vertically (it throws off the alignment of the dropdown boxes with the second cell group)
- [x] Cell Group boxes on the results panel should include cell count 
- [x] Add download and source data buttons to the results panel
- [x] Cell Group boxes on the results panel should change height based on how many tags are within them

**Medium Priority**
- [ ] ~Sorting by Effect Size shifts the padding on the results panel~
  - [x] padding is adaptive based on longest width of gene name - bug or feature?
- [ ] P-value and Effect Size numbers should be right aligned to the header (since they are numeric values)
- [x] User should be able to click on the Effect Size header itself to sort (not just the chevron)
- [x] Hovering over the tags within the cell group boxes should not change the cursor to a pointer 
- [x] Remove hover effect on table rows 
- [ ] Make cell group boxes a bit wider
  - [ ] how much wider?
- [x] Add space between the +X and ‘Search’
