### ISSUE TITLE
Add Census user agent to avoid counting internal usage in analytics

### ISSUE THREAD

**Issue by pablo-gar** [chanzuckerberg/single-cell-data-portal#7298]
## Motivation

To eliminate internal usage of Census API from analytics.

## Definition of Done

CELLxGENE features that use the Census API include a user agent to flag them. Please ask @ivirshup for how to include the agent. 

## Tasks

The following features incorporate the user agent as "internal user", @kaloster @atarashansky please add any if you see one missing

User agent:

- [ ] Gene Expression cube builder
- [ ] Cell Guide? 
- [ ] Integrated embeddings?

Then:

- [ ] Coordinate with @ainfeld to remove logs from agent in analytics dashboard
- [ ] Notify Census team

**Comment by ivirshup** [comment]
For anything that is using python `cellxgene_census` API, all that needs to be done is setting a `CELLXGENE_CENSUS_USERAGENT` environment variable. The value can be any string which will just be added to the user-agent. We're using `CZI-test` at the moment for CI in census.

If you are using `tiledbsoma` or making requests directly there will be more work to do, but you can see how to set the user agent for `s3fs`, `tiledbsoma`, and `requests` in my PR to cellxgene_census: 

* https://github.com/chanzuckerberg/cellxgene-census/pull/1193

**Comment by kaloster** [comment]
@pablo-gar I've added this to the only instance I've found on the data portal repo

**Comment by tihuan** [comment]
@kaloster sorry just wanted to check in to see if this is done already. Thanks so much!

**Comment by tihuan** [comment]
@kaloster gentle ping on this one thank you!
